tap "derailed/k9s"
tap "hashicorp/tap"
tap "tw93/tap"
brew "glib"
brew "zstd"
brew "gdk-pixbuf"
brew "harfbuzz"
brew "pango"
brew "librsvg"
brew "adwaita-icon-theme"
brew "aom"
brew "openssl@3"
brew "apr-util"
brew "argon2"
brew "asdf"
brew "ast-grep"
brew "at-spi2-core"
brew "atkmm"
brew "atkmm@2.28"
brew "awscli"
brew "azure-cli"
brew "bash-completion"
brew "bazel"
brew "bdw-gc"
brew "boost"
brew "boost-build"
brew "boost-python3"
brew "coreutils"
brew "cask"
brew "cmake"
brew "colima"
brew "deno"
brew "docker"
brew "docker-compose"
brew "duckdb"
brew "fd"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "glib-networking"
brew "gnupg"
brew "gnuplot"
brew "go"
brew "pkgconf"
brew "gobject-introspection"
brew "gpgme"
brew "gtk+3"
brew "helm"
brew "htop"
brew "jq"
brew "kubectx"
brew "libpq"
brew "mas"
brew "mcfly"
brew "mdless"
brew "mkcert"
brew "node"
brew "nvm"
brew "parallel"
brew "pgcli"
brew "pnpm"
brew "postgresql@18"
brew "procs"
brew "protobuf"
brew "reattach-to-user-namespace"
brew "redis", restart_service: :changed
brew "ripgrep"
brew "ruff"
brew "speedtest-cli"
brew "starship"
brew "tmux"
brew "tokei"
brew "tree"
brew "uv"
brew "watch"
brew "watchexec"
brew "watchman"
brew "wget"
brew "when"
brew "zsh"
brew "zsh-autosuggestions"
brew "derailed/k9s/k9s"
brew "hashicorp/tap/terraform"
brew "tw93/tap/mole"
cask "claude-code"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-monaspace"
cask "gcloud-cli"
cask "ghostty"
cask "git-credential-manager"
cask "google-chrome"
cask "medis"
cask "qlvideo"
cask "zedis"
cask "zoom"
mas "AdBlock", id: 1402042596
mas "AdGuard for Safari", id: 1440147259
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Refined GitHub", id: 1519867270
mas "Spark Desktop", id: 6445813049
mas "WhatsApp", id: 310633997
mas "Xcode", id: 497799835
cargo "cargo-expand"
cargo "cargo-sort"
cargo "cargo-udeps"
cargo "flamegraph"
cargo "starship"
